CREATE TABLE EMPLOYEE (
  ID NUMBER(10) NOT NULL,
  first_name VARCHAR2(20),
  last_name VARCHAR2(20),
  salary NUMBER(10),
  PRIMARY KEY (id)
);

CREATE SEQUENCE employee_sequence START WITH 1;

COMMIT;
